export interface RequestData {
    id: string;
    client: string;
    requestType: 'New License' | 'Renewal' | 'Upgrade';
    product: string;
    bundle: string;
    seats: number;
    duration: string;
    justification: string;
    dateSubmitted: string;
    status: 'Pending Review';
    submittedBy: string;
    email: string;
    desiredStart: string;
    justificationNote: string;
}

export const requestsData: RequestData[] = [
    {
        id: 'REQ-001',
        client: 'Providus Bank',
        requestType: 'New License',
        product: '3B Admin',
        bundle: 'Premium - Enterprise',
        seats: 200,
        duration: '12 months',
        justification: 'Expansion - additional team..',
        dateSubmitted: 'Jun 27, 2026',
        status: 'Pending Review',
        submittedBy: 'Binfense.innovantics.Resolver',
        email: 'foluke89@innovantics.com',
        desiredStart: 'Jul 01, 2026',
        justificationNote: 'Q4 expansion across Lagos, Abuja and Port Harcourt — 200 new team members onboarding. Current license insufficient. Premium Enterprise needed for reporting, access control and CBN compliance audit (Sept 2026).',
    },
    {
        id: 'REQ-002',
        client: 'Signature Bank',
        requestType: 'Renewal',
        product: 'Bifense',
        bundle: 'Premium - Enterprise',
        seats: 250,
        duration: '12 months',
        justification: 'Annual contract renewal..',
        dateSubmitted: 'Jun 26, 2026',
        status: 'Pending Review',
        submittedBy: 'Bifense.innovantics.Admin',
        email: 'tunde.adebayo@innovantics.com',
        desiredStart: 'Jul 15, 2026',
        justificationNote: 'Annual license renewal for the entire cybersecurity division. Current contract expires July 30, 2026. All 250 seats actively in use for threat detection and compliance monitoring across 12 branch offices.',
    },
    {
        id: 'REQ-003',
        client: 'Access Bank',
        requestType: 'Upgrade',
        product: 'Banklet',
        bundle: 'Basic - Premium',
        seats: 500,
        duration: '6 months',
        justification: 'Needs advanced reporting features.',
        dateSubmitted: 'Jun 25, 2026',
        status: 'Pending Review',
        submittedBy: 'Banklet.innovantics.Manager',
        email: 'chioma.okafor@innovantics.com',
        desiredStart: 'Jul 05, 2026',
        justificationNote: 'Current Basic plan lacks the advanced reporting and analytics dashboards required for the Q3 board presentation. Upgrade to Premium necessary to unlock real-time transaction monitoring and custom KPI dashboards for 500 operations staff.',
    },
    {
        id: 'REQ-004',
        client: 'Polaris Bank',
        requestType: 'Renewal',
        product: 'Bifense',
        bundle: 'Premium - Premium',
        seats: 300,
        duration: '12 months',
        justification: 'License expires July 07..',
        dateSubmitted: 'Jun 24, 2026',
        status: 'Pending Review',
        submittedBy: 'Bifense.innovantics.Resolver',
        email: 'aisha.mohammed@innovantics.com',
        desiredStart: 'Jul 07, 2026',
        justificationNote: 'Urgent renewal — current license expires July 7, 2026. Bifense Premium is critical for the bank\'s SOC operations and regulatory compliance framework. A lapse would result in non-compliance with CBN cybersecurity directives.',
    },
    {
        id: 'REQ-005',
        client: 'Union Bank',
        requestType: 'New License',
        product: '3B Admin',
        bundle: 'Premium - Enterprise',
        seats: 200,
        duration: '12 months',
        justification: 'Expansion - additional team..',
        dateSubmitted: 'Jun 23, 2026',
        status: 'Pending Review',
        submittedBy: '3BAdmin.innovantics.Admin',
        email: 'emeka.nwosu@innovantics.com',
        desiredStart: 'Jul 10, 2026',
        justificationNote: 'New branch expansion into South-East region requires 200 additional admin seats. Enterprise tier needed for multi-branch user management, role-based access control, and centralized audit logging across 8 new branches.',
    },
    {
        id: 'REQ-006',
        client: 'Sterling Bank',
        requestType: 'Renewal',
        product: 'Bifense',
        bundle: 'Premium - Enterprise',
        seats: 250,
        duration: '12 months',
        justification: 'Annual contract renewal..',
        dateSubmitted: 'Jun 22, 2026',
        status: 'Pending Review',
        submittedBy: 'Bifense.innovantics.Manager',
        email: 'grace.eze@innovantics.com',
        desiredStart: 'Jul 20, 2026',
        justificationNote: 'Standard annual renewal for the information security team. All 250 seats are critical for ongoing vulnerability assessment, intrusion detection, and compliance reporting. No changes to seat count or tier required.',
    },
    {
        id: 'REQ-007',
        client: 'Zenith Bank',
        requestType: 'Upgrade',
        product: 'Banklet',
        bundle: 'Basic - Premium',
        seats: 850,
        duration: '12 months',
        justification: 'Scaling to full enterprise...',
        dateSubmitted: 'Jun 20, 2026',
        status: 'Pending Review',
        submittedBy: 'Banklet.innovantics.Admin',
        email: 'daniel.johnson@innovantics.com',
        desiredStart: 'Aug 01, 2026',
        justificationNote: 'Scaling from Basic (200 seats) to Premium (850 seats) to support the full digital banking transformation initiative. Premium features including API gateway management, advanced fraud detection, and real-time analytics are essential for the H2 2026 rollout.',
    },
    {
        id: 'REQ-008',
        client: 'Globus Bank',
        requestType: 'New License',
        product: '3B Admin',
        bundle: 'Premium - Enterprise',
        seats: 1000,
        duration: '24 months',
        justification: 'New enterprise contract...',
        dateSubmitted: 'Jun 21, 2026',
        status: 'Pending Review',
        submittedBy: '3BAdmin.innovantics.Resolver',
        email: 'bukola.fadipe@innovantics.com',
        desiredStart: 'Aug 15, 2026',
        justificationNote: 'New 24-month enterprise contract for full organizational deployment. 1000 seats across all departments including operations, compliance, and customer service. Enterprise tier required for SSO integration, advanced RBAC, and dedicated support SLA.',
    },
    {
        id: 'REQ-009',
        client: 'Wema Bank',
        requestType: 'Upgrade',
        product: 'Banklet',
        bundle: 'Basic - Premium',
        seats: 500,
        duration: '6 months',
        justification: 'Needs advanced reporting features.',
        dateSubmitted: 'Jun 19, 2026',
        status: 'Pending Review',
        submittedBy: 'Banklet.innovantics.Manager',
        email: 'ngozi.obi@innovantics.com',
        desiredStart: 'Jul 01, 2026',
        justificationNote: 'Upgrading 500 seats from Basic to Premium to gain access to advanced reporting features, custom workflow automation, and enhanced API rate limits. Required for the upcoming ALAT digital banking platform upgrade scheduled for Q3 2026.',
    },
    {
        id: 'REQ-010',
        client: 'Keystone Bank',
        requestType: 'New License',
        product: 'Bifense',
        bundle: 'Premium - Enterprise',
        seats: 150,
        duration: '12 months',
        justification: 'New cybersecurity deployment..',
        dateSubmitted: 'Jun 18, 2026',
        status: 'Pending Review',
        submittedBy: 'Bifense.innovantics.Admin',
        email: 'olu.bankole@innovantics.com',
        desiredStart: 'Jul 25, 2026',
        justificationNote: 'First-time deployment of Bifense across the IT security and compliance departments. 150 seats needed for threat intelligence, vulnerability management, and automated compliance reporting to meet new CBN cybersecurity framework requirements.',
    },
];
